# Generated by Django 4.0.6 on 2022-10-02 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='investors_depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('coin', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='investors_payed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('coin', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=500)),
                ('country', models.CharField(default=None, max_length=200)),
                ('img', models.ImageField(upload_to='img%y')),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('wallet_ad', models.CharField(max_length=100)),
                ('trans_date1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('withdrw', models.BooleanField(null=True, verbose_name='successful')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_ad', models.CharField(max_length=100)),
                ('coin', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=12)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('profileimg', models.ImageField(default='t.png', upload_to='profile_images')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt1', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('coin1', models.CharField(blank=True, max_length=50)),
                ('trans_date1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bol', models.BooleanField(null=True, verbose_name='successful')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt1', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('plans', models.CharField(blank=True, max_length=100)),
                ('trans_date1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bol', models.BooleanField(default=False, verbose_name='completed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
